### ISSUE TITLE
Clarify the available value for the variable {{docSearchJSVersion}}

### ISSUE THREAD

**Issue by t2hnd** [algolia/docsearch-website#52]
Regarding this page: https://docsearch.algolia.com/docs/dropdown/

There is a variable {{docSearchJSVersion}} as a part of the URL in the link tag and the script tag to load realted files.
However, the available value for this version is not clear in this document.
The version information is currently available in the [release page](https://github.com/algolia/docsearch/releases), so how about adding a line to explain it as well as mentioning 'latest' option is available to load the latest version?

```
<!-- Before the closing </head> -->
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/docsearch.js@{{docSearchJSVersion}}/dist/cdn/docsearch.min.css"
/>

<!-- Before the closing </body> -->
<script src="https://cdn.jsdelivr.net/npm/docsearch.js@{{docSearchJSVersion}}/dist/cdn/docsearch.min.js"></script>
```

**Comment by shortcuts** [comment]
Closing since the documentation has moved to https://github.com/algolia/docsearch. Don't hesitate to suggest changes there!

The version has been fixed in the snippet!
