### ISSUE TITLE
Image in dark mode is unreadable

### ISSUE THREAD

**Issue by mdubus** [algolia/docsearch-website#59]
Hi ! 👋

[This image](https://github.com/algolia/docsearch-website/blob/master/src/pages/index.js#L117) on the [homepage](https://docsearch.algolia.com/) has text that is written with dark colors.

In dark mode, it is unreadable : 

![Capture d’écran 2021-05-25 à 15 14 54](https://user-images.githubusercontent.com/30866152/119506579-5977ae80-bd6e-11eb-9dd5-f2bc1ed14d01.png)

If possible, it would be nice to have a different image or update the existing one with colors that would work in both modes 😀

Thanks ! 

Edit : Images on [this page](https://docsearch.algolia.com/docs/how-do-we-build-an-index) are also unreadable in dark mode 😉

**Comment by shortcuts** [comment]
Closing since the documentation has moved to https://github.com/algolia/docsearch. Don't hesitate to suggest changes there!

(Doc and front page have been updated)
