### ISSUE TITLE
Run the crawl from the Docker image Windows

### ISSUE THREAD

**Issue by joeluis111** [algolia/docsearch-website#60]
Hi, Hoping someone can help me
I'm Trying to setup the searchbar for a docusaurus environment using algolia.

This is my config.json 
 {
  "index_name": "dev_Docusaurus_DA",
  "start_urls": [
    "http://localhost:3000/"
  ],
  "sitemap_urls": [
    "https://docusaurus.io/sitemap.xml"
  ],
  "sitemap_alternate_links": true,
  "stop_urls": [
    "/tests"
  ],
  "selectors": {
    "lvl0": {
      "selector": "(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]",
      "type": "xpath",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": "header h1",
    "lvl2": "article h2",
    "lvl3": "article h3",
    "lvl4": "article h4",
    "lvl5": "article h5, article td:first-child",
    "lvl6": "article h6",
    "text": "article p, article li, article td:last-child"
  },
  "strip_chars": " .,;:#",
  "custom_settings": {
    "separatorsToIndex": "_",
    "attributesForFaceting": [
      "language",
      "version",
      "type",
      "docusaurus_tag"
    ],
    "attributesToRetrieve": [
      "hierarchy",
      "content",
      "anchor",
      "url",
      "url_without_anchor",
      "type"
    ]
  },
  "conversation_id": [
    "833762294"
  ],
  "nb_hits": 46250
}

My problem is the use of the docker command:
docker run -it --env-file=.env -e "CONFIG=$(cat /path/to/your/config.json | jq -r tostring)" algolia/docsearch-scraper
I Know that cat can't be used on windows
I've been Trying to use this command instead:
docker run -it --env-file=.env -e "CONFIG=$(" jq -r tostring C:\Users\jjimenez\documentos_ayuda/config.json")" algolia/docsearch-scraper

Please Help

**Comment by shortcuts** [comment]
Closing since the documentation has moved to https://github.com/algolia/docsearch. Don't hesitate to suggest changes there!

Please check this issue: https://github.com/algolia/docsearch/issues/922
Issue related to the scraper should be opened in this repository: https://github.com/algolia/docsearch-scraper
