### ISSUE TITLE
How to use docsearch@alpha with CDN?

### ISSUE THREAD

**Issue by kai687** [algolia/docsearch-website#62]
I struggled to use the alpha release of DocSearch via CDN.
Specifically, I don't know from where to include the CSS for DocSearch 3 alpha.

It would be nice to clarify this in the docs.

**Comment by shortcuts** [comment]
Closing since the documentation has moved to https://github.com/algolia/docsearch. Don't hesitate to suggest changes there!

DocSearch v3 documentation is available here: https://docsearch.algolia.com/docs/DocSearch-v3
